ALTER TABLE "Product"
ADD COLUMN "discount_price" DOUBLE PRECISION,
ADD COLUMN "is_active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Product"
ALTER COLUMN "updated_at" DROP DEFAULT;